### ISSUE TITLE
Analysis View

### ISSUE THREAD

**Issue by chichha** [HE-Arc/AnalyChess#11]
# Task
- [x]  View
  - [x] Grid
  - [x] Annotation tool
  - [x] Comment
  - [x]  History
- [x] Logic
  - [x] Save
  - [x] Share
  - [x] Make history work
  - [x] Save annotation in a JSON
    - [x] Write annotation locally
    - [ ] Send the JSON to the serve
    

 # Info
Receive a JSON with movement :

```json
{
"moves" : [
  [x0,y0, x1,y1],
],
"end_piece" : object (chess piece)
}


```

- [0,0] -> [0,4] - a1 -> a5
- Arrival Piece  (promotion, prise en passant)
